### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by dq-mlnck** [DownQuark-Work/downquark.blockchainWeb3.PWA_FatRedBird#14]
# Design System Checklist
> https://www.designsystemchecklist.com

**TOC**

- [[#Design language|Design language]]
	- [[#Brand|Brand]]
	- [[#Logo|Logo]]
	- [[#Guidelines|Guidelines]]
- [[#Design tokens|Design tokens]]
	- [[#Colour|Colour]]
	- [[#Layout|Layout]]
	- [[#Typography|Typography]]
	- [[#Iconography|Iconography]]
- [[#Core components|Core components]]
	- [[#Avatar|Avatar]]
	- [[#Badge|Badge]]
	- [[#Banner|Banner]]
	- [[#Button|Button]]
	- [[#Card|Card]]
	- [[#Carousel|Carousel]]
	- [[#Dropdown|Dropdown]]
	- [[#Icon|Icon]]
	- [[#Input checkbox|Input checkbox]]
	- [[#Input radio|Input radio]]
	- [[#Input text|Input text]]
	- [[#Input switch|Input switch]]
	- [[#List|List]]
	- [[#Loading indicator|Loading indicator]]
	- [[#Modal|Modal]]
	- [[#Tabs|Tabs]]
	- [[#Toast|Toast]]
	- [[#Tooltip|Tooltip]]
- [[#Tooling|Tooling]]
	- [[#Design|Design]]
	- [[#Development|Development]]
- [[#Project management|Project management]]
	- [[#Task management|Task management]]
	- [[#Communications|Communications]]
	- [[#Analytics|Analytics]]

---
## Design language
Like any language, a design language is a methodical way of communicating with your audience through your approach to product design. It’s the cornerstone of consistent customer experiences.

---
### Brand
> Brand drives every single decision you make when building new products or features. A good brand is much more than a name and a logo. It’s the values that define your unique identity and what makes you stand out from others.

- [ ] Vision
  - Why you exist, what your values are and how they’ll help guide the future of your product.
- [ ] Design principles
  - The considerations that guide the basis of your practice. They outline how you approach design from a philosophical perspective and help with everyday decisions.

- [ ] Tone of voice
  - A clear tone of voice defines how you speak to your audience at every moment in their journey, helping them get wherever they want to go.

- [ ] Terminology
  - Create the standard terms and phrases that need to be kept the same throughout the user experience, speeding up the design process and unifying your voice.

- [ ] Writing guidelines
  - Every consistent experience needs watertight writing. Laying down the foundations for your house style early keeps everything in line with consistent grammar, style choices and action-oriented language to help your design.

### Logo
> Most customers form an opinion about a product in seconds. In most cases, your logo will be the first brand asset someone sees. It’s all about making the right first impression. A distinctive logo helps users recognise a product immediately and gives them the essence of your branding.

- [ ] Monochrome version
  - A monochrome version of your logo that looks good on top of photography or when it’s printed with a poor quality printer.

- [ ] Small use guidance
  - Your logo must perform well and be recognisable at all sizes. Tips for using your logo in these cases will minimise the risk of it being misused.

- [ ] Placement and clearance guidance
  - Your logo must come with clear guidance on how to place it and how to preserve its space since it lives along with other content.

- [ ] Usage guidance
  - These are the logo crimes, providing contextual examples of what to (not) do with your logo.

- [ ] Different file formats
  - Providing a variety of formats for the vector version of your logo will make it easier for others to work and prevent anyone from redrawing it.

### Guidelines
> Providing guidance on how to approach common UX patterns will allow your organisation to establish a consistent approach and a consistent user experience on any platform.

- [ ] Accessibility
  - Guidelines for how you approach accessibility and how you leverage colour, hierarchy and assistive technologies to help your users.

- [ ] User onboarding
  - How you onboard your users to your product or a new feature and give them a great experience from the start.

- [ ] Notifications and permissions
  - Guardrails for how to write for the components that make up your designs, from style and technical rules to channeling your tone of voice correctly through copy.

- [ ] Microcopy guidelines
  - The standard way to write for the components in your design system. These take platform conventions and best practices for writing all into consideration.

---
## Design tokens
Variables that store values for the base layer of your design system, like colour and typography. They’re used in components, so changes on this level will resonate throughout the whole system.

---
### Colour
> Not only an efficient way to showcase your brand, but also an efficient way to communicate with your users. Colour palettes created with purpose over aesthetics in mind can help you create intuitive design patterns by adding meaning to your interface.

- [ ] Accessibility
  - Make sure to have accessible pairings between the main colours in your palette. More importantly, make sure that your background and text colours have at least an AA standard contrast ratio between them.

- [ ] Functional colours
  - Besides your brand colours, make sure to have colours defined and made into variables for functions like disabled states, backgrounds, actions and high contrast text.

- [ ] Dark mode
  - Preparing a dark mode version of your colour palette will allow your design system to adapt to dark mode and respect what your user wants to see.

- [ ] Guidelines
  - Provide guidelines on how and when to use the colours in your palette, what to keep in mind when working with them and how not to use them.

### Layout
> A well thought out layout goes a long way. Consistent use of a grid and spacing makes it easier for your users to scan the user interface and grasp the content.

- [ ] Units
  - Units are the most granular building blocks for layout. Defining a set of values with consistent increments (such as 4, 8, 12 and 16 for a 4-point system) will provide you with the foundation when you’re designing your grid and spacing values.

- [ ] Grid
  - Every layout should sit on a grid that brings order and hierarchy to the interface. Define a grid separately for mobile, tablet and desktop devices with columns, gutters, and margins so your interface can adapt to any platform easily.

- [ ] Breakpoints
  - Predefine the screen sizes and orientations your grid will adapt to.

- [ ] Spacing
  - Horizontal and vertical rhythm plays a big role in a layout. You should provide easy methods for adding space between interface elements independent of your grid.

### Typography
> Typography is one of the main ways you surface content in products. A clear hierarchy and contrasting styles in your typography scale will make things easier to read and help with the overall structure of your product. It’s also an opportunity to visualise your brand character and presence.

- [ ] Responsiveness
  - Desktop devices can usually afford to have bigger font sizes compared to mobile devices. Creating a typography scale that adapts to the viewport size will help with a more meaningful hierarchy and layout.

- [ ] Grid relation
  - Font sizes and leading should match your grid to allow better pairing between text and other UI elements. A good example of this is text paired with icons with bounding boxes.

- [ ] Readability
  - Optimising the letter spacing (tracking), line height (leading) and line length for your typography scale will help with the readability of text.

- [ ] Performance
  - Custom fonts need to be downloaded before they can be displayed, especially on the web. Make sure that you have sensible fallbacks and fast loading time for your typography assets. Using system fonts solves this performance problem.

- [ ] Guidelines
  - Provide guidelines on how and when to use the pairings in your typography scale, what to keep in mind when working with them and how not to use them.

### Iconography
> Icons are symbols that represent functionality or content. They’re especially recognisable and helpful in user interfaces since their meaning can be understood at a glance. hough they can be used just for decoration, their full potential can be realised when they’re used meaningfully and consistently.

- [ ] Accessibility
  - For icons that convey a meaning or serve a function, add the necessary support for screen readers. You can skip this for decorative icons.

- [ ] Style
  - Make sure that your icon family makes visual sense as a whole. Picking an outlined or filled style and sticking with it will lead to better visual consistency and predictability.

- [ ] Naming
  - Name your icons based on what they are, not what they represent. For instance, a trash icon should be named trash, not delete. You can still add related keywords to improve discoverability.

- [ ] Relation with grid
  - Draw your icons in a bounding box that plays well with your grid. This makes for a better pairing with other UI elements. A good example of this would be icons with bounding boxes paired with text.

- [ ] Sizes
  - Provide different sizes for icons that correlate to your grid. Provide a minimum size and remove unnecessary detail for your icons for smaller sizes.

- [ ] Keywords
  - Adding keywords will improve the discoverability of each icon and provide a better user experience for anyone using your system.

- [ ] Reserved icons
  - Reserving icons that represent common actions will prevent their use in any other context. System icons for navigation or adding and deleting are a good example. This leads to a more intuitive user experience.

- [ ] Guidelines
  - Provide guidelines on how and when to use icons, what to keep in mind when working with them and how not to use them

---
## Core components
Components are the main building blocks for user interfaces. Building a reusable component library enhances your product development workflow by reducing design and tech debt and speeding up the process. Core components can’t be broken down into granular pieces without losing their meaning.

---
### Avatar
> Avatars are used to show a thumbnail of a user photo or a visual representation of any other type of content.

- [ ] Image
  - Avatars should mask an image into their shape and work with any image size since they may get this image from unknown data sources.
    
- [ ] Image fallback
  - There should be fallbacks when there’s no image available. This can be done with placeholder images or initials.
    
- [ ] Accessibility
  - Always provide a description for screen readers describing what’s displayed on the avatar image instead of just naming its role.
    
- [ ] Sizes
  - There are many contexts to use avatars and they all require different sizes for the component. For average projects use at least 2-3 different sizes and make sure there’s at least a small size available.
    
- [ ] Icon
  - Avatars can be used with an icon instead of an image to emphasize areas that don’t necessarily have (or need) an image associated with it.
    
- [ ] Background colours
  - When used with icons or text, there has to be a background colour from the design system colour tokens applied to the avatar shape. Make sure that icons and text have enough contrast ratio with the background according to the WCAG AA standard.

### Badge
> Badges are elements that represent the status of an object or user input value.

- [ ] Appearance
  - Badges may play various roles in your product and having a predefined colour for each role should help users understand their meaning. When changing colours, make sure the text has enough contrast ratio with the background according to the WCAG AA standard.
    
- [ ] Dismissible action
  - Badges can be used as a dynamic way to display selected values and there should be a way to dismiss them.

### Banner
> Banners display an actionable message used as a prominent way of communicating with your users.

- [ ] Appearance
  - Banners are used to display different types of messages and it’s important to differentiate their visual appearance based on the role they’re playing. If you’re using background colours for role differentiation, make sure there’s enough contrast ratio with the content according to the WCAG AA standard.
    
- [ ] Area for icons or images
  - Banners can supplement their message using a supporting icon or image. They shouldn’t be used instead of text content.
    
- [ ] Actions
  - Actions in banners should relate to its text and provide a way to react to the message sent to the user.
    
- [ ] Dismissible action
  - Don’t overwhelm the user with banners on the page and include a dismissable action. That may be either a separate close button or one of the actions provided.
    
- [ ] Accessibility
  - If a banner dynamically appears on the page, it should be announced to the user by their assistive technology.
    
- [ ] Responsiveness
  - Banners should adapt to the viewport size. This usually means that they become full-width for mobile to save some space.

### Button
> Buttons are interactive elements used for single-step actions.

- [ ] Hover state
  - Clearly show that the button is interactive when it gets hovered with a mouse cursor.
    
- [ ] Active state
  - Used when a button gets pressed. The same state can be used to represent the button responsible for toggling another element on the page while that element is visibly opened.
    
- [ ] Focused state
  - Used when a button gets selected through keyboard navigation.
    
- [ ] Icon support
  - Icons easily communicate the purpose of the button when used next to its label or can be used without text when there’s not enough space. Make sure that the accessibility label is provided when used with an icon only.
    
- [ ] Disabled
  - Visually shows that a button is not interactive and restricts it from being pressed.
    
- [ ] Loading
  - Used when users have to wait for the result of their action after they press a button. If a spinner is used to display this state make sure that it’s not changing the original button width or height.
    
- [ ] Full-width
  - By default buttons take the width of their content, but they should also come with a full width variant that works well in mobile devices.
    
- [ ] Variants
  - When using multiple buttons, there should be a way to differentiate between primary and secondary actions. Buttons may play different roles for the user or be used on different types of surfaces and they have to change the way they look.
    
- [ ] Sizes
  - Buttons can be used in different areas of the website and may have multiple predefined sizes. On mobile, tappable areas have to be a minimum of 48px to be accessible according to iOS and Android accessibility guidelines.

### Card
> Cards are used to group information about subjects and their related actions.

- [ ] Supports any type of content
  - Cards are one of the most used components in the product, so they have to be flexible enough to support any other components placed in them.
    
- [ ] Information structure
  - No matter how flexible cards are, it’s important for cards to have a specific structure for its elements for product consistency.
    
- [ ] Supports media sections
  - One of the most popular scenarios for using cards is mixing them with media content. The most popular options are having a full-width area on top of the content or full-height area at one of the card’s sides.
    
- [ ] Supplementary actions
  - Cards can be used with actions usually placed at the bottom of the card, or the card itself can be tappable and represent an action.
    
- [ ] Responsiveness
  - On mobile viewports cards are usually full-width in order to save space for the content.

### Carousel
> Carousels stack the same type of items and allows scrolling through them horizontally.

- [ ] Navigation controls
  - Carousels should have easy-to-find navigation controls for scrolling through content.
    
- [ ] Supports any content
  - Carousels can be used in different contexts and shouldn’t be limited to a specific child component. In some scenarios you might want items within the same carousel to differ from each other.
    
- [ ] Items width customisation
  - For simple products, it might be fine to use multiple predefined sizes for carousel items. For more flexibility, it’s good to provide a way to define a custom width.
    
- [ ] Touch events support
  - Carousels should be scrollable on touch devices. Some of the best practices are to use native scrolling and to make sure you’re supporting the same behaviour for all touch devices, not just mobile phones.
    
- [ ] Keyboard navigation
  - It should be possible to scroll through content with keyboard arrows when focused on navigation controls.
    
- [ ] Responsiveness
  - It’s good practice to hide or reduce the size of navigation controls for mobile viewports to improve the visibility of the content.

### Dropdown
> Dropdowns are used to display a contextual subview with a list of actions or content related to the area where the dropdown is.

- [ ] Supports any type of content
  - Dropdowns may be used in a lot of contexts like date pickers, language selection or other product features.
    
- [ ] Action menu
  - One of the most used scenarios for dropdowns is providing an action menu for the user, so it’s useful to have this layout defined.
    
- [ ] Focus trapping
  - Once the dropdown’s opened, the focus should work only for elements inside the dropdown. When it’s closed, the focus should move to the dropdown trigger.
    
- [ ] Close action
  - Either some actions inside the dropdown should close it or there should be a separate close button. Also, it’s good practice to close the dropdown when a user clicks outside.
    
- [ ] Keyboard navigation
  - It should be possible to navigate through dropdown children elements with the keyboard and close it with an Esc key.
    
- [ ] Dynamic positioning
  - Dropdown content should be displayed based on the current position of the trigger element on the screen and always visible to the user.
    
- [ ] Responsiveness
  - Dropdown content should be adapted for mobile viewpoints as it may take a lot of space on desktops.

### Icon
> The icon component is a way to align the way iconography static assets are displayed in the product.

- [ ] Sizes
  - Icons should have a number of predefined sizes to provide a holistic experience across the product. Typography pairings may be used for these size values to ensure that they are aligned with the text sizes.
    
- [ ] Colours
  - Icons should be using values from the design system colour palette. Using parent element text colour for icon fill colour can make this automatic.

### Input checkbox
> An input checkbox is a form element used for selecting one or multiple options.

- [ ] Checked state
  - Used when the checkbox is selected and will use its value for the form submission.
    
- [ ] Disabled state
  - Prevents checkbox interactions and removes its value from the form submission.
    
- [ ] Indeterminate state
  - Used when the checkbox has children selectable elements and only some of them are selected.
    
- [ ] Label
  - There should be a text label linked with the checkbox field. Clicking the label should also trigger the checkbox selection.
    
- [ ] Error state
  - The error state is used for form validation errors when the error is related to the checkbox field only. Always use a text error along with changing the colour of the field.
    
- [ ] Keyboard support
  - Checkbox selections should be triggered with the Space key. Using native elements for this should provide this kind of interaction out of the box.
    
- [ ] Checkbox group
  - Checkboxes can be grouped to work with multiple values at the same time.

### Input radio
> An input radio is a form element used for selecting one option from a list.

- [ ] Checked state
  - Used when the radio is selected and will use its value for the form submission. A radio input can’t be unselected by pressing it again.
    
- [ ] Disabled state
  - Prevents radio interactions and removes its value from the form submission.
    
- [ ] Label
  - There should be a text label linked with the radio field. Clicking the label should also trigger the radio selection.
    
- [ ] Error state
  - The error state is used for form validation errors when the error is related to the radio field only. Always use a text error along with changing the colour of the field.
    
- [ ] Keyboard support
  - A radio selection should be triggered when the Space key is pressed. Using native elements for this should provide this kind of interaction out of the box.
    
- [ ] Radio group
  - Radio inputs should always be used in a group. If one of them is selected, it can be deselected only by choosing another radio.

### Input text
> Input text lets users enter and edit text.

- [ ] Disabled state
  - Prevents input interactions and removes its value from the form submission.
    
- [ ] Placeholder
  - When there’s no value entered, show a placeholder with a potential value example. Don’t use placeholders as labels for the inputs.
    
- [ ] Label
  - There should be a text label linked with the text field. Clicking the label should move the focus to the field.
    
- [ ] Error state
  - The error state is used for form validation errors when the error is related to the text field only. Always use a text error along with changing the colour of the field.
    
- [ ] Autocomplete
  - When applicable, adding support for the HTML autocomplete attribute will allow users to easily enter different data types.
    
- [ ] Icon support
  - Icons are used to describe input methods, express a text field state or provide additional functionality.

### Input switch
> Input switches toggle the state of a single item. Compared to the input checkbox, their changes usually apply without any additional submission.

- [ ] Checked state
  - Used when an input switch is turned on. It’s better to provide an additional way to indicate the checked state besides changing its colour when applicable.
    
- [ ] Disabled state
  - Prevents interacting with an input switch.
    
- [ ] Label
  - There should be a text label linked with the switch field. Clicking the label should also trigger the input selection.
    
- [ ] Keyboard support
  - A switch selection should be triggered when the Space key is pressed.

### List
> Lists define the layout of the page content or groups of elements stacking them vertically or horizontally.

- [ ] Supports any type of content
  - Lists can be used in any context from page-level layout to managing offsets between granular components. hey should work with any component used inside.
    
- [ ] Horizontal stacking
  - Lists can be used for inline elements and they have to manage how they’re stacked horizontally, including handling offsets between multiple rows of elements.
    
- [ ] Divided variant
  - Lists with dividers are the best practice advised by many platform guidelines (especially on mobile).
    
- [ ] Supports actionable content
  - Sometimes lists are used for grouping tappable components, where the whole area of the list item should be clickable.

### Loading indicator
> The loading indicator shows that an operation’s being performed and how long the process will take.

- [ ] Linear and non-linear variants
  - Depending on the context and the component it’s used for, the loading indicator can be represented either with linear or with a non-linear (e.g. circular) variant.
    
- [ ] Determinate or indeterminate wait time
  - In some cases, the wait time can’t be determined. The loading indicator should be shown until the loading finishes or an error happens. In other cases, it’s better to indicate how much time’s left until the loading is done.
    
- [ ] Light variant
  - The loading indicator should respect its parent element background and provide a variant to be used on darker background colours.
    
- [ ] Reduced motion
  - The loading indicator should be synced with the system motion settings and reduce its animation speed when reduced motion settings are turned on.

### Modal
> Modals are containers appearing in front of the main content to provide critical information or an actionable piece of content.

- [ ] Supports any type of content
  - Like any other container, modals can be used in different scenarios and you should be able to use it with any other component inside.
    
- [ ] Supplementary actions
  - Since content in the modal may be actionable, it’s important to have an area for action elements. This area is usually located at the bottom of the modal container.
    
- [ ] Close action
  - Modals should provide a clear way to be closed as they’re blocking content when open. This may be either a separate close button or one of the supplementary actions.
    
- [ ] Information structure
  - Even though modals can be used as an empty container for the content, they need a defined information structure to provide a holistic experience. It may include defining how titles and subtitles look by default or where an action element’s area is.
    
- [ ] Keyboard navigation support
  - It should be possible to close a modal by pressing the Esc key and all the focusable elements inside the modal container should be accessible with keyboard navigation.
    
- [ ] Focus trapping
  - Once a modal is opened, the focus should be moved to the first element inside the modal and should be looped within the modal container. Closing the modal should return the focus to the last focused element on the page.

### Tabs
> Tabs organise navigation between multiple pages or content sections.

- [ ] Active button state
  - There should be a clear differentiation between selected and unselected tab buttons.
    
- [ ] Button icon support
  - Icons help show the purpose of the tab buttons when used next to its label.
    
- [ ] Equally-sized tab buttons
  - Tabs can be used in a relatively small-sized container where you need to switch between a definite number of sections. For such scenarios, it’s better to support a variant where the button’s area is divided equally.
    
- [ ] Keyboard navigation
  - All tab buttons should be focusable and navigation between the tab’s component should be accessible from the keyboard.
    
- [ ] Responsiveness
  - If all tabs on mobile don’t fit into the viewport, users should still have access to all tab buttons. Ways to solve this can be making the button area scrollable for mobile or showing a More button containing a dropdown with the rest of the buttons.

### Toast
> Toasts provide short meaningful feedback messages about the action results.

- [ ] Dismissed automatically
  - Toast messages shouldn’t interrupt the user flow, block the screen for a long time or require additional action from the user.
    
- [ ] Action support
  - Besides displaying the message, toasts may also provide an action related to the message like undoing an action.
    
- [ ] Handles multiple instances
  - Even though it doesn’t happen often, toasts can be called from multiple sources at the same time and all resulting toasts should be queued. It’s good practice not to show all the messages at the same time.
    
- [ ] Accessibility
  - Toast messages should be announced by the voice assistive technology and their action should be easily accessible from the keyboard.
    
- [ ] Responsiveness
  - Toasts should be aligned with the mobile viewport and their action should be easily reachable for tapping.

### Tooltip
> Tooltips are desktop-only components that display additional information when hovering over or focusing on an element.

- [ ] Keyboard hover support
  - Tooltips should be accessible when an element is focused using the keyboard.
    
- [ ] Dynamic positioning
  - Tooltip content should be displayed based on the current position of the trigger element on the screen and always visible to the user.
    
- [ ] Hover timeout
  - Having a small timeout before triggering a tooltip will help to prevent occasionally showing tooltips while users move their mouse cursor.
    
- [ ] Light variant
  - The tooltip should respect its parent element background and provide a variant to be used on darker background colours.
    
- [ ] Instant transition for element groups
  - If there’s a group of elements using tooltips, hovering over another element while a tooltip’s already active shouldn’t trigger the animation.

---
## Tooling
To make things efficient for anyone using your design system, make tooling essential. Find the workflows where you can integrate things with the tools people use. This helps organically spread your design system and make it crucial to people’s daily work.

---
### Design
> The UI and UX in a design system need to be tied to development as much as possible. The tools in this checklist should help designers and developers work better together.

- [ ] Design editor
  - There are many design editors available in the market today with the most popular names being Sketch, Figma and Adobe XD. If you're unsure which route to go down it's often best to speak with your team.
    
- [ ] Plugins
  - Most popular Design Editors (Sketch and Figma, especially) come with third-party plugin support. Whilst it's best to use the editors in-built tools for laying out your components, plugins can bring in a range of useful data to populate them.
    
- [ ] Version control
  - Having your design versioned with semantic versioning will allow you to easily align design with development, roll back faulty changes and release changes in code and design at the same time.
    
- [ ] Contribution guidelines
  - Define the process of contributing to the UI and UX of the design system and document it in a discoverable place to make it easier for everyone to contribute.
    

### Development
> One of the main challenges in developing a design system isn’t building the components. It’s making your code stable, easy to read and contribute to.

- [ ] Component catalog
  - Isolate your UI components’ environment outside of your product codebase to make sure they’re not dependent on any global dependencies and can be easily reused.
    
- [ ] Documentation
  - Having your code documented is key to driving adoption and reducing the load on the contributors.
    
- [ ] Code style
  - Having a defined code style helps align the way code’s written in the system and increases development velocity. It should be automated with the tools provided for each platform.
    
- [ ] Unit testing
  - Every part of the design system should be covered with unit tests. Once your system’s adopted, any change in the isolated environment may affect how the product works.
    
- [ ] Accessibility testing
  - Design systems should cover accessibility as much as possible. Making this automatic reduces the risk of inaccessible components or user flows in the product.
    
- [ ] Semantic versioning
  - Version your code with semantic versioning that dictates how version numbers are assigned and incremented.
    
- [ ] Release strategy
  - Design system releases should be automated and ideally use scripts ran locally or in remote CI pipelines to prevent broken releases.
    
- [ ] Commit message guidelines and changelog
  - Automate the generation of your changelog by adopting a commit message guidelines that categorise and define the changes being made.
    
- [ ] MR templates
  - Create merge request templates that outline the change being proposed to facilitate productive discussions.
    
- [ ] Contribution guidelines
  - Define the process of contributing to the code of the design system. Document everything in a discoverable place to make it easier for everyone to contribute.

---
## Project management
Design systems are no different than any other project your team might take on. In order to successfully build and maintain one, you need a clear strategy that’s well executed daily, and you‘ll need to create opportunities for your colleagues to give feedback to help share your design system together.

---
### Task management
> Solid task management and workflows are a crucial step in executing any project. Adopting a methodology like Agile or Kanban helps you cover a lot of ground.

- [ ] Roadmap
  - Setting your short and long term vision and mapping things out helps you decide the steps to take, understand your place in the bigger picture and prioritise day-to-day tasks.
    
- [ ] Milestones
  - Define milestones that act as bigger epics in your project management with the help of your roadmap. These will help you understand your progress.
    
- [ ] Ticketing
  - Make it easier to track your day-to-day progress by using ticketing software like Jira, Trello or GitHub. This’ll make it easier for others to submit feature proposals or bug reports.
    

### Communications
> Your users play a great role in shaping your design system. Creating communication channels where they can raise their voices helps you keep track of how they’re using your system. It’ll also improve their sense of ownership and the adoption of your system.

- [ ] Community meetings
  - Arrange community meetings with everyone who uses the design system. Share your knowledge and make proposals to improve the sense of community.
    
- [ ] Communication channel
  - Most product development work happens digitally, so create a digital channel where people can reach out and ask questions.
    
- [ ] Open hours
  - Create open hours in which you can engage your audience in a more private setting where you can discuss things in more detail. You can also use these as peer coding or peer design opportunities.
    
- [ ] FAQ
  - To save everyone time, define which questions are asked frequently by your audience and document them in a discoverable place.
    

### Analytics
> Data isn’t the only driving factor when it comes to the development of design systems. Keeping a sharp eye on how your system’s used in the development process and the end product can inform your go-forward strategy.

- [ ] Component analytics
  - Track the usage of your components. For development you can use built-in tools like Figma’s Design System Analytics. For the end product you can have a separate way of tracking per platform depending on the technology.
    
- [ ] Error logging
  - Implement a way to track and pinpoint component-related outages in your product.
    
- [ ] Tooling analytics
  - Track what tools are being used for your design system. Find out which ones are used the most and which features are the most popular.
    
- [ ] Service and health metrics
  - Define service and health metrics for your design system to set a benchmark on how well you’re doing. Common examples can be the number of tickets closed, improvements made or bugs fixed.
